name: Trigger auto deployment for ref4-company-research

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: [main]
    paths:
      - "app/**"
      - ".github/workflows/ref4-company-research-AutoDeployTrigger-758021c0-16b8-4537-8953-5362fc3814fe.yml"

  # Allow mannually trigger
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Create and populate .env file
        env:
          AZURE_OPENAI_SERVICE: ${{ secrets.AZURE_OPENAI_SERVICE }}
          AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
          AZURE_OPENAI_COMPLETION_DEPLOYMENT: ${{ secrets.AZURE_OPENAI_COMPLETION_DEPLOYMENT }}
          AZURE_OPENAI_CHAT_DEPLOYMENT: ${{ secrets.AZURE_OPENAI_CHAT_DEPLOYMENT }}
          AZURE_OPENAI_EMBEDDING_DEPLOYMENT: ${{ secrets.AZURE_OPENAI_EMBEDDING_DEPLOYMENT }}
          REDIS_NAME: ${{ secrets.REDIS_NAME }}
          REDIS_KEY: ${{ secrets.REDIS_KEY }}
        run: |
          touch .env
          echo AZURE_OPENAI_API_TYPE="azure" >> .env
          echo AZURE_OPENAI_SERVICE="$AZURE_OPENAI_SERVICE" >> .env
          echo AZURE_OPENAI_API_KEY="$AZURE_OPENAI_API_KEY" >> .env
          echo AZURE_OPENAI_API_VERSION="2023-05-15" >> .env
          echo AZURE_OPENAI_COMPLETION_DEPLOYMENT="$AZURE_OPENAI_COMPLETION_DEPLOYMENT" >> .env
          echo AZURE_OPENAI_CHAT_DEPLOYMENT="$AZURE_OPENAI_CHAT_DEPLOYMENT" >> .env
          echo AZURE_OPENAI_EMBEDDING_DEPLOYMENT="$AZURE_OPENAI_EMBEDDING_DEPLOYMENT" >> .env
          echo REDIS_NAME="$REDIS_NAME" >> .env
          echo REDIS_KEY="$REDIS_KEY" >> .env
          echo REDIS_CATEGORY_COMMON="company_common" >> .env
          echo REDIS_CATEGORY_TOPICS="company_topics" >> .env
          echo REDIS_INDEX_NAME="embedding_index" >> .env

          echo "cat .env"
          cat .env

          echo "ls -a ."
          ls -a .

          echo "Move .env file to backend folder"
          mv .env app/backend/

          echo "ls -a ${{ github.workspace }}"
          ls -a ${{ github.workspace }}
        shell: bash

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.REF4COMPANYRESEARCH_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.REF4COMPANYRESEARCH_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.REF4COMPANYRESEARCH_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}/app
          registryUrl: swoaidemoregistry.azurecr.io
          registryUsername: ${{ secrets.REF4COMPANYRESEARCH_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.REF4COMPANYRESEARCH_REGISTRY_PASSWORD }}
          containerAppName: ref4-company-research
          resourceGroup: aoai_refer_art_rg
          imageToBuild: swoaidemoregistry.azurecr.io/ref4-company-research:${{ github.sha }}
          dockerfilePath: Dockerfile
